metrics:
  _partial_: true
  _target_: aprl.appareil.run
  dry: false
  params:
    max_lat: 43.0
    max_lon: -55.0
    max_time: '2017-12-31'
    method: default
    min_lat: 33.0
    min_lon: -65.0
    min_time: '2017-01-01'
    sat: c2
    study_path: data/downloads/method_outputs/default.nc
    study_var: ssh
  parts:
    _01_dl_track:
      _partial_: true
      _target_: copernicusmarine.python_interface.get.get
      dataset_id:
        _target_: oost_dc_ose_2021.mods.cmems_get.duacs_l3
        sat: c2
      force_download: true
      output_directory: data/downloads/ref/c2
      overwrite_output_data: true
      regex:
        _target_: oost_dc_ose_2021.mods.cmems_get.month_regex_from_date
        max_time: '2017-12-31'
        min_time: '2017-01-01'
    _02_prepare_track:
      _partial_: true
      _target_: oost_dc_ose_2021.mods.prepare_track.prepare_track
      input_paths:
        _target_: glob.iglob
        dir_fd: null
        include_hidden: false
        pathname: data/downloads/ref/c2/**/*.nc
        recursive: true
        root_dir: null
      output_path: data/prepared/ref/c2.nc
      preprocess:
        _partial_: true
        _target_: oost_dc_ose_2021.mods.prepare_track.preprocess_track
        max_lat: 43.0
        max_lon: -55.0
        max_time: '2017-12-31'
        min_lat: 33.0
        min_lon: -65.0
        min_time: '2017-01-01'
      sort_paths: true
    _03_interp_on_track:
      _partial_: true
      _target_: oost_dc_ose_2021.mods.interp_on_track.interp_on_track
      grid_paths: data/downloads/method_outputs/default.nc
      output_path: data/prepared/method_outputs/default_on_track.nc
      preprocess_grid:
        _partial_: true
        _target_: oost_dc_ose_2021.mods.interp_on_track.preprocess_map
        ssh_var: ssh
      preprocess_track: null
      track_paths: data/prepared/ref/c2.nc
    _04_1_lambdax:
      _partial_: true
      _target_: oost_dc_ose_2021.mods.lambdax.lambdax
      delta_t: 0.9434
      length_scale: 1000.0
      output_lambdax_path: data/metrics/lambdax_default.json
      output_psd_path: data/prepared/method_outputs/psd_default.nc
      preprocess_ref:
        _target_: aprl.utils.kw2a
        fn:
          _target_: hydra_zen.funcs.get_obj
          path: operator.itemgetter
        ssh_var: ssh
      preprocess_study:
        _target_: aprl.utils.kw2a
        fn:
          _target_: hydra_zen.funcs.get_obj
          path: operator.itemgetter
        ssh_var: ssh
      ref_paths: data/prepared/ref/c2.nc
      segment_overlapping: 0.25
      study_paths: data/prepared/method_outputs/default_on_track.nc
      velocity: 6.77
    _04_2_mu:
      _partial_: true
      _target_: oost_dc_ose_2021.mods.mu.mu
      output_path: data/metrics/mu_default.json
      preprocess_ref:
        _target_: aprl.utils.kw2a
        fn:
          _target_: hydra_zen.funcs.get_obj
          path: operator.itemgetter
        ssh_var: ssh
      preprocess_study:
        _target_: aprl.utils.kw2a
        fn:
          _target_: hydra_zen.funcs.get_obj
          path: operator.itemgetter
        ssh_var: ssh
      ref_paths: data/prepared/ref/c2.nc
      study_paths: data/prepared/method_outputs/default_on_track.nc
  to_run:
  - _01_dl_track
  - _02_prepare_track
  - _03_interp_on_track
  - _04_1_lambdax
  - _04_2_mu
input_data:
  _partial_: true
  _target_: aprl.appareil.run
  dry: false
  params:
    max_lat: 44.0
    max_lon: -54.0
    max_time: '2018-02-01'
    min_lat: 32.0
    min_lon: -66.0
    min_time: '2016-12-01'
    sat: ???
    sat_list:
    - alg
    - h2ag
    - j2g
    - j2n
    - j3
    - s3a
  parts:
    _01_dl_track:
      _partial_: true
      _target_: copernicusmarine.python_interface.get.get
      dataset_id:
        _target_: oost_dc_ose_2021.mods.cmems_get.duacs_l3
        sat: ???
      force_download: true
      output_directory: ???
      overwrite_output_data: true
      regex:
        _target_: oost_dc_ose_2021.mods.cmems_get.month_regex_from_date
        max_time: '2018-02-01'
        min_time: '2016-12-01'
    _02_prepare_track:
      _partial_: true
      _target_: oost_dc_ose_2021.mods.prepare_track.prepare_track
      input_paths:
        _target_: glob.iglob
        dir_fd: null
        include_hidden: false
        pathname: ???
        recursive: true
        root_dir: null
      output_path: ???
      preprocess:
        _partial_: true
        _target_: oost_dc_ose_2021.mods.prepare_track.preprocess_track
        max_lat: 44.0
        max_lon: -54.0
        max_time: '2018-02-01'
        min_lat: 32.0
        min_lon: -66.0
        min_time: '2016-12-01'
      sort_paths: true
  to_run:
  - _01_dl_track
  - _02_prepare_track
