[methods.4dvarnet]
url = "https://s3.eu-west-2.wasabisys.com/oceanbench-data-registry/dvc/a5/2381e9409cb7c6cf9be980bda9aced"
var = "rec_ssh"

[methods.duacs]
url = "https://s3.eu-west-2.wasabisys.com/oceanbench-data-registry/dvc/95/7d74696fbf5f2b6d0c528757951b8a"
var = "ssh"


[methods.oi_demo]
url = "https://s3.eu-west-2.wasabisys.com/melody/quentin_cloud/ocb_oi_demo.nc"
var = "ssh"
