name: Compute DC OSE 2021 metrics
on:
  push:
    branches:
    - leaderboard/*
jobs:
  reproduce-metrics:
    runs-on: [ubuntu-latest]
    steps:
      - name: Is commit from github actions
        id: check_author
        run: |
          echo "skip=${{github.author == 'github-actions'}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        if: ${{ steps.check_author.outputs.skip == 'false' }}
      - uses: mamba-org/setup-micromamba@v1
        if: ${{ steps.check_author.outputs.skip  == 'false' }}
        with:
          micromamba-version: 'latest'
          environment-file: env-s3.yaml
          environment-name: ci
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Install repo
        shell: bash -el {0}
        run: |
          pip install -e .
      - name: Reproduce metrics
        if: ${{ steps.check_author.outputs.skip  == 'false' }}
        shell: bash -el {0}
        id: reproduce_metrics
        run: |
          cd datachallenge
          export DIAGNOSTIC_STAGES=$(dvc stage list --name-only | grep 'diagnostics')
          export METRIC_STAGES=$(dvc stage list --name-only | grep 'diagnostics/metric')
          echo $METRIC_STAGES
          echo "Pulling data"
          echo "$DIAGNOSTIC_STAGES" | xargs -t -I{} dvc pull --allow-missing --with-deps  {}
          echo "Metrics status"
          echo "$METRIC_STAGES" | xargs -t -I{} dvc status {}
          echo "Reproducing"
          echo "$METRIC_STAGES" | xargs -t -I{} if [[ $(dvc status {} --json) == "{}" ]]; then dvc repro -k --allow-missing {}; fi 
      - name: push new files
        if: ${{ (steps.check_author.outputs.skip == 'false') && steps.stages_to_run.outputs.stages }}
        shell: bash -l {0}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.aws_key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.aws_secret}}
          AWS_DEFAULT_REGION: ${{secrets.aws_region}}
        run: dvc --cd datachallenge push -r s3 ${{steps.stages_to_run.outputs.stages}}
      - name: dump metrics report
        if: ${{ (steps.check_author.outputs.skip == 'false') }}
        shell: bash -l {0}
        run: |
          cd datachallenge
          echo 'Data Challenge OSE Gulfstream 2021\n' > leaderboard.md
          dvc metrics show --json | python scripts/format_metrics.py >> leaderboard.md
          cat report.md
      - name: Commit changes
        if: ${{ (steps.check_author.outputs.skip == 'false') }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update dc_ose_2021 datachallenge'
          add: 'dvc.lock leaderboard.md full_config.yaml'
          cwd: './datachallenge'
          push: true
