name: Compute DC OSE 2021 metrics
on:
  push:
    branches:
    - leaderboard/*
jobs:
  reproduce-metrics:
    runs-on: [ubuntu-latest]
    steps:
      - name: Is commit from github actions
        id: check_author
        run: |
          echo "skip=${{github.author == 'github-actions'}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        if: ${{ steps.check_author.outputs.skip == 'false' }}
      - uses: mamba-org/setup-micromamba@v1
        if: ${{ steps.check_author.outputs.skip  == 'false' }}
        with:
          micromamba-version: 'latest'
          environment-file: env-s3.yaml
          environment-name: ci
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: install pipelines
        if: ${{ steps.check_author.outputs.skip  == 'false' }}
        shell: bash -el {0}
        run: |
          pip install .
      - name: install jq
        if: ${{ steps.check_author.outputs.skip  == 'false' }}
        uses: dcarbone/install-jq-action@v2
      - name: compute_stages
        if: ${{ steps.check_author.outputs.skip  == 'false' }}
        shell: bash -el {0}
        id: metrics_to_recompute
        run: |
          cd leaderboard
          dvc  pull data/prepared/ref/* data/prepared/method_outputs/*
          STATUS=$(dvc status --json)
          echo $STATUS
          STAGES=$(echo "$STATUS" | jq -r '[keys[] | select(contains("diagnostics/metric"))] | join(" ")')
          echo $STAGES
          echo "stages=$STAGES" >> "$GITHUB_OUTPUT"
      - name: reproduce datachallenge results
        shell: bash -el {0}
        if: ${{ (steps.check_author.outputs.skip == 'false') && steps.metrics_to_recompute.outputs.stages }}
        run: |
          dvc --cd leaderboard freeze diagnostics/fetch_reference_data
          dvc --cd leaderboard repro -k --pull --allow-missing ${{steps.stages_to_run.outputs.stages}}
          dvc --cd leaderboard unfreeze diagnostics/fetch_reference_data
      - name: push new files
        if: ${{ (steps.check_author.outputs.skip == 'false') && steps.stages_to_run.outputs.stages }}
        shell: bash -l {0}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.aws_key}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.aws_secret}}
          AWS_DEFAULT_REGION: ${{secrets.aws_region}}
        run: dvc --cd leaderboard push -r s3 ${{steps.stages_to_run.outputs.stages}}
      - name: dump metrics report
        if: ${{ (steps.check_author.outputs.skip == 'false') }}
        shell: bash -l {0}
        run: |
          cd leaderboard
          echo 'Data Challenge OSE Gulfstream 2021\n' > report.md
          dvc metrics show --json | python scripts/format_metrics.py >> report.md
          cat report.md
      - name: Commit changes
        if: ${{ (steps.check_author.outputs.skip == 'false') }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update dc_ose_2021 leaderboard'
          add: 'dvc.lock report.md'
          cwd: './leaderboard'
          push: true
